[package]
name = "devtoolbox-infrastructure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "DevToolbox local filesystem and settings adapters."

[dependencies]
async-trait = "0.1"
devtoolbox-core = { path = "../core" }
encoding_rs = "0.8"
feed-rs.workspace = true
quick-xml.workspace = true
regex.workspace = true
reqwest.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
url.workspace = true

[lints]
workspace = true

