[package]
name = "devtoolbox-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "DevToolbox document workflows and application DTOs."

[dependencies]
async-trait = "0.1"
devtoolbox-core = { path = "../core" }
parking_lot.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
async-trait = "0.1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true

