[package]
name = "devtoolbox-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "DevToolbox Tauri desktop adapter."

[dependencies]
devtoolbox-application = { path = "../../crates/application" }
devtoolbox-core = { path = "../../crates/core" }
devtoolbox-infrastructure = { path = "../../crates/infrastructure" }
devtoolbox-runtime = { path = "../../crates/runtime" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2", features = [] }
parking_lot.workspace = true
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tauri-plugin-wdio = { version = "1", optional = true }
tauri-plugin-wdio-webdriver = { version = "1", optional = true }

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true

[features]
e2e = ["dep:tauri-plugin-wdio", "dep:tauri-plugin-wdio-webdriver"]
